import * as stylex from "@stylexjs/stylex";
import { appColors } from "../app-tokens.stylex";

export const dialogStyles = stylex.create({
  overlay: {
    position: "fixed",
    zIndex: 100,
    inset: 0,
    backgroundColor: "rgb(91 112 131 / 40%)",
  },
  dialog: {
    position: "fixed",
    zIndex: 101,
    top: "50%",
    left: "50%",
    width: "min(600px, calc(100% - 32px))",
    overflowY: "auto",
    color: appColors.text,
    backgroundColor: appColors.background,
    borderColor: appColors.border,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 16,
    boxShadow: "0 24px 64px rgb(0 0 0 / 50%)",
    fontFamily: '"Manrope Variable", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    transform: "translate(-50%, -50%)",
  },
  header: {
    display: "grid",
    height: 53,
    paddingInline: 16,
    gridTemplateColumns: "36px 1fr auto",
    alignItems: "center",
    gap: 12,
    borderBottomColor: appColors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
  },
  title: { margin: 0, fontSize: 20, fontWeight: 700, lineHeight: "24px" },
  primaryButton: {
    minHeight: 32,
    paddingInline: 16,
    color: "#0f1419",
    backgroundColor: { default: "#eff3f4", ":hover": "#d7dbdc" },
    borderWidth: 0,
    borderRadius: 9999,
    font: "inherit",
    fontWeight: 700,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.6 },
  },
  closeButton: {
    display: "grid",
    width: 36,
    height: 36,
    minHeight: 0,
    padding: 0,
    color: appColors.text,
    backgroundColor: { default: "transparent", ":hover": "rgb(239 243 244 / 10%)" },
    placeItems: "center",
  },
  focusRing: {
    outlineColor: { default: null, ":focus-visible": appColors.blue },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineWidth: { default: null, ":focus-visible": 2 },
    outlineOffset: { default: null, ":focus-visible": 2 },
  },
});
